[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
customasm = "0.13.5"
wasm-bindgen = { version = "0.2.92" }

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true
