[package]
name = "icmc-emulator"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.92" }

[profile.release]
panic = "abort"
lto = "fat"
opt-level = 3
