[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.92" }
assembler = { path = "../assembler" }
compiler = { path = "../compiler" }
emulator = { path = "../emulator" }
fs = { path = "../fs" }
